name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  token:
    required: true
    description: 'GitHub token with "repo" scope'
runs:
  using: 'node16'
  main: 'dist/index.js'
